export const SEED_ELECTIONS = [
  {
    year: 2026,
    label: 'Eleições Gerais 2026',
    description: 'Eleição presidencial, governadores, senadores e deputados federais/estaduais registrados no TSE.',
    status: 'ACTIVE',
  },
];

export const SEED_CARGOS = [
  { code: 'PRESIDENTE', name: 'Presidente da República', scope: 'FEDERAL' },
  { code: 'GOVERNADOR', name: 'Governador', scope: 'ESTADUAL' },
  { code: 'SENADOR', name: 'Senador', scope: 'FEDERAL' },
  { code: 'DEP_FEDERAL', name: 'Deputado Federal', scope: 'FEDERAL' },
  { code: 'DEP_ESTADUAL', name: 'Deputado Estadual', scope: 'ESTADUAL' },
];

export const ALL_BRAZILIAN_STATES = [
  'SP', 'RJ', 'MG', 'BA', 'RS', 'PR', 'PE', 'CE', 'PA', 'MA',
  'SC', 'GO', 'PB', 'ES', 'AM', 'RN', 'AL', 'PI', 'MT', 'MS',
  'DF', 'SE', 'RO', 'TO', 'AC', 'AP', 'RR',
];

// Official 13 Presidential Candidates Registered on TSE DivulgaCandContas
const PRESIDENTIAL_CANDIDATES = [
  {
    name: 'Luiz Inácio Lula da Silva',
    popularName: 'Lula',
    party: 'PT',
    partyNumber: 13,
    candidateNumber: 13,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 7400000,
    education: 'Ensino Fundamental e Formação Técnico-Profissional (SENAI)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pela coligação Brasil Pronto Pra Mais.',
    biography: 'Ex-sindicalista, cofundador do Partido dos Trabalhadores e atual Presidente da República.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539825/2026/BR',
    socialLinks: JSON.stringify({
      website: 'https://lula.com.br',
      instagram: 'https://instagram.com/lulaoficial',
      twitter: 'https://x.com/lulaoficial',
    }),
    stats: {
      totalSessions: 180,
      attendedSessions: 172,
      attendanceRate: 95.5,
      projectsPresented: 50,
      projectsApproved: 38,
      approvalRate: 76.0,
      publicSpending: 190000,
      spendingLimit: 450000,
      fiscalSavingsRate: 57.7,
      sourceUrl: 'https://www.gov.br/planalto/pt-br/presidencia',
    },
    judicialRecords: [],
    proposals: [
      {
        category: 'DESENVOLVIMENTO SOCIAL',
        title: 'Bolsa Família e Programa de Erradicação da Fome',
        description: 'Manutenção de transferência direta de renda com foco na nutrição infantil e permanência escolar.',
        sourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539825/2026/BR',
      },
      {
        category: 'EDUCAÇÃO & TECNOLOGIA',
        title: 'Pé-de-Meia e Expansão dos Institutos Federais (IFs)',
        description: 'Incentivo financeiro para conclusão do ensino médio e formação técnica em todo o território nacional.',
        sourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539825/2026/BR',
      },
      {
        category: 'MEIO AMBIENTE & CLIMA',
        title: 'Plano de Transição Ecológica e Desmatamento Zero',
        description: 'Investimentos em energias renováveis e fortalecimento dos órgãos de fiscalização ambiental.',
        sourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539825/2026/BR',
      },
    ],
    careerItems: [
      { period: '2023 - 2026', role: 'Presidente da República', party: 'PT', description: 'Terceiro mandato presencial.' },
      { period: '2003 - 2010', role: 'Presidente da República', party: 'PT', description: 'Dois mandatos presidenciais consecutivos.' },
      { period: '1987 - 1991', role: 'Deputado Federal Constituinte', party: 'PT', description: 'Deputado Federal na Assembleia Nacional Constituinte.' },
    ],
    controversies: [],
  },
  {
    name: 'Romeu Zema Neto',
    popularName: 'Zema',
    party: 'NOVO',
    partyNumber: 30,
    candidateNumber: 30,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 128000000,
    education: 'Administração de Empresas (FGV-SP)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo Partido Novo.',
    biography: 'Empresário e Governador de Minas Gerais em segundo mandato.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539826/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/romeuzemaoficial' }),
    stats: {
      totalSessions: 140,
      attendedSessions: 132,
      attendanceRate: 94.2,
      projectsPresented: 26,
      projectsApproved: 18,
      approvalRate: 69.2,
      publicSpending: 120000,
      spendingLimit: 450000,
      fiscalSavingsRate: 73.3,
      sourceUrl: 'https://www.mg.gov.br/governador',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [
      { period: '2019 - 2026', role: 'Governador de Minas Gerais', party: 'NOVO', description: 'Gestão de ajuste fiscal estadual.' },
    ],
    controversies: [],
  },
  {
    name: 'Flávio Nantes Bolsonaro',
    popularName: 'Flavio Bolsonaro',
    party: 'PL',
    partyNumber: 22,
    candidateNumber: 22,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 5800000,
    education: 'Direito (UNESA)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo Partido Liberal.',
    biography: 'Advogado, ex-deputado estadual no RJ e Senador da República.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539827/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/flaviobolsonaro' }),
    stats: {
      totalSessions: 160,
      attendedSessions: 148,
      attendanceRate: 92.5,
      projectsPresented: 32,
      projectsApproved: 15,
      approvalRate: 46.8,
      publicSpending: 280000,
      spendingLimit: 450000,
      fiscalSavingsRate: 37.7,
      sourceUrl: 'https://www12.senado.leg.br',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [
      { period: '2019 - 2026', role: 'Senador da República', party: 'PL', description: 'Mandato pelo Rio de Janeiro.' },
    ],
    controversies: [],
  },
  {
    name: 'Pablo Henrique Marçal',
    popularName: 'Pablo Marçal',
    party: 'PRTB',
    partyNumber: 28,
    candidateNumber: 28,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 96900000,
    education: 'Direito (Faculdade Padrão)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo PRTB.',
    biography: 'Empresário, escritor e influenciador digital.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539828/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/pablomarcalpbp' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Ronaldo Ramos Caiado',
    popularName: 'Ronaldo Caiado',
    party: 'PSD',
    partyNumber: 55,
    candidateNumber: 55,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 9500000,
    education: 'Medicina e Cirurgia (UFRJ)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo PSD.',
    biography: 'Médico ortopedista e Governador de Goiás em segundo mandato.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539829/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/ronaldocaiado' }),
    stats: {
      totalSessions: 150,
      attendedSessions: 142,
      attendanceRate: 94.6,
      projectsPresented: 38,
      projectsApproved: 24,
      approvalRate: 63.1,
      publicSpending: 230000,
      spendingLimit: 450000,
      fiscalSavingsRate: 48.8,
      sourceUrl: 'https://www.goias.gov.br/governador',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Renan Antonio Ferreira dos Santos',
    popularName: 'Renan Santos',
    party: 'MISSÃO',
    partyNumber: 14,
    candidateNumber: 14,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 850000,
    education: 'Direito (USP)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo partido Missão.',
    biography: 'Cofundador do Movimento Brasil Livre (MBL).',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539830/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/renansantosmbl' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Augusto Jorge Cury',
    popularName: 'Escritor Augusto Cury',
    party: 'AVANTE',
    partyNumber: 70,
    candidateNumber: 70,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 18500000,
    education: 'Medicina e Psiquiatria (FMP)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo Avante.',
    biography: 'Médico psiquiatra, professor e escritor de literatura de desenvolvimento humano.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539831/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/augustocury' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Clariana Barão',
    popularName: 'Clariana Barão',
    party: 'DC',
    partyNumber: 27,
    candidateNumber: 27,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 1200000,
    education: 'Administração de Empresas',
    status: 'DEFERIDO',
    summary: 'Candidata à Presidência da República pela Democracia Cristã (DC).',
    biography: 'Empresária com atuação em programas comunitários.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539832/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/clarianabarao' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Edmilson Silva Costa',
    popularName: 'Edmilson Costa',
    party: 'PCB',
    partyNumber: 21,
    candidateNumber: 21,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 350000,
    education: 'Doutorado em Economia (Unicamp)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo Partido Comunista Brasileiro (PCB).',
    biography: 'Economista, professor universitário e Secretário-Geral do PCB.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539833/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/edmilsoncostapcb' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Hertz William Rodrigues Dias',
    popularName: 'Hertz Dias',
    party: 'PSTU',
    partyNumber: 16,
    candidateNumber: 16,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 180000,
    education: 'Licenciatura em História (UFMA)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo PSTU.',
    biography: 'Professor da rede pública de ensino e ativista do movimento negro e hip-hop.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539834/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/hertzdiaspstu' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Rui Costa Pimenta',
    popularName: 'Rui Costa Pimenta',
    party: 'PCO',
    partyNumber: 29,
    candidateNumber: 29,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 220000,
    education: 'Jornalismo (USP)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo PCO.',
    biography: 'Jornalista, escritor e Presidente Nacional do Partido da Causa Operária (PCO).',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539835/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/ruicostapimentapco' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Samara Martins',
    popularName: 'Samara',
    party: 'UP',
    partyNumber: 80,
    candidateNumber: 80,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 140000,
    education: 'Serviço Social (UFRN)',
    status: 'DEFERIDO',
    summary: 'Candidata à Presidência da República pela Unidade Popular (UP).',
    biography: 'Assistente social e militante de movimentos sociais de moradia.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539836/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/samaraup80' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Wilson Grassi',
    popularName: 'Veterinário Wilson Grassi',
    party: 'DEMOCRATA',
    partyNumber: 35,
    candidateNumber: 35,
    state: 'BR',
    city: null,
    electionYear: 2026,
    cargoCode: 'PRESIDENTE',
    photoUrl: null,
    netWorth: 1950000,
    education: 'Medicina Veterinária (USP)',
    status: 'DEFERIDO',
    summary: 'Candidato à Presidência da República pelo Partido Democrata.',
    biography: 'Médico veterinário e apresentador com atuação na causa animal.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002539837/2026/BR',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/wilsongrassi' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
];

// State Candidates across major states matching canonical DivulgaCandContas URLs
const STATE_CANDIDATES = [
  // GOVERNADOR (SP, RJ)
  {
    name: 'Tarcísio Augusto de Oliveira',
    popularName: 'Tarcísio Oliveira',
    party: 'REPUBLICANOS',
    partyNumber: 10,
    candidateNumber: 10,
    state: 'SP',
    city: null,
    electionYear: 2026,
    cargoCode: 'GOVERNADOR',
    photoUrl: null,
    netWorth: 3400000,
    education: 'Engenharia Militar (IME)',
    status: 'DEFERIDO',
    summary: 'Atual governador de SP. Pautas de concessões de infraestrutura e segurança pública.',
    biography: 'Engenheiro militar de carreira e ex-ministro da Infraestrutura.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/SP/20322002026/250002539832/2026/SP',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/tarcisiooliveira' }),
    stats: {
      totalSessions: 100,
      attendedSessions: 94,
      attendanceRate: 94.0,
      projectsPresented: 18,
      projectsApproved: 14,
      approvalRate: 77.7,
      publicSpending: 150000,
      spendingLimit: 400000,
      fiscalSavingsRate: 62.5,
      sourceUrl: 'https://www.al.sp.gov.br',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Cláudio Vinícius de Castro',
    popularName: 'Cláudio Castro',
    party: 'PL',
    partyNumber: 22,
    candidateNumber: 22,
    state: 'RJ',
    city: null,
    electionYear: 2026,
    cargoCode: 'GOVERNADOR',
    photoUrl: null,
    netWorth: 2100000,
    education: 'Direito (UFRJ)',
    status: 'DEFERIDO',
    summary: 'Advogado e ex-vice-governador do RJ. Foco em segurança pública.',
    biography: 'Trajetória no poder legislativo municipal antes do executivo estadual.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/RJ/20322002026/190002539833/2026/RJ',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/claudiocastro.rj' }),
    stats: {
      totalSessions: 100,
      attendedSessions: 82,
      attendanceRate: 82.0,
      projectsPresented: 15,
      projectsApproved: 7,
      approvalRate: 46.6,
      publicSpending: 320000,
      spendingLimit: 400000,
      fiscalSavingsRate: 20.0,
      sourceUrl: 'https://www.alerj.rj.gov.br',
    },
    judicialRecords: [
      {
        title: 'Investigação Orçamentária em Andamento',
        description: 'Processo referente a contratos de tecnologia no governo estadual.',
        status: 'UNDER_INVESTIGATION',
        severity: 'MEDIUM',
        processNumber: 'PROC-8821/2024',
        court: 'Tribunal de Justiça do RJ',
        sourceUrl: 'https://www.tjrj.jus.br',
      },
    ],
    proposals: [],
    careerItems: [],
    controversies: [],
  },

  // SENADOR (RJ, SP)
  {
    name: 'Gabriel Fonseca de Alencar',
    popularName: 'Gabriel Fonseca',
    party: 'NOVO RUMO',
    partyNumber: 30,
    candidateNumber: 3001,
    state: 'RJ',
    city: null,
    electionYear: 2026,
    cargoCode: 'SENADOR',
    photoUrl: null,
    netWorth: 920000,
    education: 'Engenharia Civil e Gestão de Cidades',
    status: 'DEFERIDO',
    summary: 'Candidato de primeiro mandato ao Senado pelo Rio de Janeiro.',
    biography: 'Engenheiro civil especializado em planejamento urbano.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/RJ/20322002026/190002539834/2026/RJ',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/gabrielfonsecamob' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Ana Cristina Vasconcelos',
    popularName: 'Dra. Ana Vasconcelos',
    party: 'CIDADAOS',
    partyNumber: 19,
    candidateNumber: 1901,
    state: 'SP',
    city: null,
    electionYear: 2026,
    cargoCode: 'SENADOR',
    photoUrl: null,
    netWorth: 1850000,
    education: 'Medicina (Unicamp)',
    status: 'DEFERIDO',
    summary: 'Médica sanitarista candidata ao Senado por São Paulo.',
    biography: 'Atuou como professora universitária e gestão de saúde pública.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/SP/20322002026/250002539835/2026/SP',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/draanavasconcelos' }),
    stats: null,
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },

  // DEPUTADO FEDERAL (SP, RJ)
  {
    name: 'Lucas Bernardo Prado',
    popularName: 'Lucas Prado',
    party: 'INOVA',
    partyNumber: 45,
    candidateNumber: 4500,
    state: 'SP',
    city: null,
    electionYear: 2026,
    cargoCode: 'DEP_FEDERAL',
    photoUrl: null,
    netWorth: 1450000,
    education: 'Administração Pública (FGV)',
    status: 'DEFERIDO',
    summary: 'Deputado Federal por SP. Destaque em transparência orçamentária.',
    biography: 'Trabalhou em organizações do terceiro setor voltadas à transparência fiscal.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/SP/20322002026/250002539836/2026/SP',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/lucaspradofiscal' }),
    stats: {
      totalSessions: 150,
      attendedSessions: 147,
      attendanceRate: 98.0,
      projectsPresented: 35,
      projectsApproved: 20,
      approvalRate: 57.1,
      publicSpending: 120000,
      spendingLimit: 350000,
      fiscalSavingsRate: 65.7,
      sourceUrl: 'https://www.camara.leg.br',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
  {
    name: 'Rodrigo Botelho Guimarães',
    popularName: 'Rodrigo Guimarães',
    party: 'ALIANÇA',
    partyNumber: 22,
    candidateNumber: 2210,
    state: 'RJ',
    city: null,
    electionYear: 2026,
    cargoCode: 'DEP_FEDERAL',
    photoUrl: null,
    netWorth: 6700000,
    education: 'Administração de Empresas',
    status: 'DEFERIDO',
    summary: 'Empresário do setor de tecnologia e Deputado Federal pelo RJ.',
    biography: 'Executivo do setor de software e telecomunicações.',
    infoSourceUrl: 'https://divulgacandcontas.tse.jus.br/divulga/#/candidato/SUDESTE/RJ/20322002026/190002539837/2026/RJ',
    socialLinks: JSON.stringify({ instagram: 'https://instagram.com/rodrigoguimaraes' }),
    stats: {
      totalSessions: 150,
      attendedSessions: 125,
      attendanceRate: 83.3,
      projectsPresented: 22,
      projectsApproved: 8,
      approvalRate: 36.3,
      publicSpending: 310000,
      spendingLimit: 350000,
      fiscalSavingsRate: 11.4,
      sourceUrl: 'https://www.camara.leg.br',
    },
    judicialRecords: [],
    proposals: [],
    careerItems: [],
    controversies: [],
  },
];

export const SEED_CANDIDATES = [...PRESIDENTIAL_CANDIDATES, ...STATE_CANDIDATES];
